import {
  AutoComplete,
  Cascader,
  Checkbox,
  DatePicker,
  Input,
  InputNumber,
  Mentions,
  Radio,
  Rate,
  Select,
  Slider,
  Switch,
  TimePicker,
  Transfer,
  TreeSelect,
  Upload,
} from 'antd';

export const lib = {
  AutoComplete: AutoComplete,
  Cascader: Cascader,
  Checkbox: Checkbox,
  CheckboxGroup: Checkbox.Group,
  DatePicker: DatePicker,
  MonthPicker: DatePicker.MonthPicker,
  RangePicker: DatePicker.RangePicker,
  WeekPicker: DatePicker.WeekPicker,
  YearPicker: DatePicker.YearPicker,
  Input: Input,
  Search: Input.Search,
  TextArea: Input.TextArea,
  InputGroup: Input.Group,
  Password: Input.Password,
  InputNumber: InputNumber,
  Mentions: Mentions,
  Radio: Radio,
  RadioGroup: Radio.Group,
  Rate: Rate,
  Select: Select,
  Slider: Slider,
  Switch: Switch,
  TimePicker: TimePicker,
  Transfer: Transfer,
  TreeSelect: TreeSelect,
  Upload: Upload,
};
